### ISSUE TITLE
output space 

### ISSUE THREAD

**Issue by lunebellec** [courtois-neuromod/cneuromod#9]
I am reviewing the outputs of fmriprep. It looks like it is using the (non-linear wrapping) outputs in both MNI152NLin2009cAsymand MNI152NLin6Asym . I haven't been able to find a clean description of these templates, although I assume the first is the MNI templates released by Vlad Fonov which are also used in niak, and google tells me through various sources that MNI152NLin6Asym is a template that ships with FSL. @bpinsard do you know why this second template space was selected?

For most primary cneuromod analyses, we will do pure single subject analysis. It may be more interesting to use both the `T1w` (for volumetric analyses) and `fsnative` (for surface based analyses), and drop non-linear wrapping altogether. It should still be possible to resample data in non-linear space if need to compare maps across subjects - using ants resampling tools (or this project maybe at some point, although it does not seem to be active at the moment https://github.com/poldracklab/nitransforms)

**Comment by bpinsard** [comment]
The second space is used internally by fmriprep, I will remove it in the next iteration on the pipeline because it is not useful and uses a lot of storage space.
For more info on the templates https://www.templateflow.org/ 

I agree that we could output into individual anat space, but I am not sure about fully dropping the MNI space. One could want to work on timeseries for between subject analysis (eg ISC-like).
